# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46a460798fc58bc92470534b80685383b8b0e02dc69ae81287dc6e014d92ebaa5d3dcaf78658cba65364b8fc3179372dfd749f2b6acb125fe87a1125827c0327

test:
  secret_key_base: 187e027df4a30c518dfa6cc6b08acc912b021126f02ecb54f2ff09d21118d1a9193d17226560be94351cfea510d38474e858dc94fe011851c431edc171dca849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
